const FIELD_LABELS: Record<string, string> = {
  first_name: "Prénom",
  last_name: "Nom",
  full_name: "Nom complet",
  name: "Nom",
  title: "Titre",
  label: "Libellé",
  known_name: "Nom connu",
  species: "Espèce",
  race: "Espèce",
  age: "Âge",
  apparent_age: "Âge apparent",
  sex: "Sexe",
  gender: "Genre",
  biological_stage: "Stade biologique",
  origin: "Origine",
  birthplace: "Lieu de naissance",
  current_location: "Lieu actuel",
  location: "Lieu",
  region: "Région",
  realm: "Royaume",
  kingdom: "Royaume",
  state: "État",
  profession: "Profession",
  occupation: "Occupation",
  social_status: "Statut social",
  status: "Statut",
  role: "Rôle",
  affiliation: "Affiliation",
  faction: "Faction",
  guild: "Guilde",
  clan: "Clan",
  house: "Maison",
  family: "Famille",
  relationship: "Relation",
  relationship_type: "Type de relation",
  relation: "Relation",
  parent: "Parent",
  father: "Père",
  mother: "Mère",
  sibling: "Fratrie",
  children: "Enfants",
  description: "Description",
  known_description: "Description connue",
  summary: "Résumé",
  known_summary: "Résumé connu",
  notes: "Notes",
  content: "Contenu",
  text: "Texte",
  source: "Source",
  confidence: "Confiance",
  certainty: "Certitude",
  epistemic_status: "Statut de connaissance",
  knowledge_status: "Statut de connaissance",
  appearance: "Apparence",
  visual_identity: "Identité visuelle",
  current_visual_state: "État visuel actuel",
  visual_state: "État visuel",
  build: "Corpulence",
  face: "Visage",
  hair: "Cheveux",
  eyes: "Yeux",
  distinctive_features: "Signes distinctifs",
  usual_clothing: "Tenue habituelle",
  hp: "Points de vie",
  hp_current: "Points de vie actuels",
  hp_max: "Points de vie maximum",
  mana: "Mana",
  mana_current: "Mana actuel",
  mana_max: "Mana maximum",
  official_rank: "Rang officiel",
  rank: "Rang",
  grade: "Grade",
  level: "Niveau",
  mastery_level: "Niveau de maîtrise",
  qualitative_level: "Niveau qualitatif",
  value: "Valeur",
  category: "Catégorie",
  quantity: "Quantité",
  weight: "Poids",
  unit_weight: "Poids unitaire",
  equipped: "Équipé",
  condition: "État",
  cost: "Coût",
  known_effect: "Effet connu",
  principle: "Principe",
  objectives: "Objectifs",
  reward: "Récompense",
  reward_announced: "Récompense annoncée",
  game_time: "Temps en jeu",
  date: "Date",
  period: "Période",
  observation: "Observation",
  observations: "Observations",
  official_observations: "Observations officielles",
  feeling: "Ressenti",
  qualitative_progress: "Progression qualitative",
  progress_feeling: "Ressenti de progression",
  last_progress: "Dernière progression",
  severity: "Gravité",
  awakened: "Éveillé",
  observed_manifestations: "Manifestations observées",
  card_number: "Numéro de carte",
  identifier: "Identifiant",
  holder_name: "Titulaire",
  disciplinary_status: "Statut disciplinaire",
  result: "Résultat",
  territory: "Territoire",
  habitat: "Habitat",
  behavior: "Comportement",
  behaviour: "Comportement",
  known_strengths: "Forces connues",
  strengths: "Forces",
  known_weaknesses: "Faiblesses connues",
  weaknesses: "Faiblesses",
  tactics: "Tactiques",
  threat_level: "Niveau de menace",
  customs: "Coutumes",
  culture: "Culture",
  language: "Langue",
  religion: "Religion",
  law: "Loi",
  laws: "Lois",
  economy: "Économie",
  population: "Population",
  ruler: "Dirigeant",
  leader: "Dirigeant",
  capital: "Capitale",
  current: "Actuel",
  priority: "Priorité",
  importance: "Importance",
  distance_km: "Distance",
  location_precision: "Précision de localisation",
  map_precision: "Précision cartographique",
  encyclopedia_category: "Catégorie d’encyclopédie",
  encyclopedia_include: "Inclure dans l’encyclopédie",
};

const ENTITY_LABELS: Record<string, string> = {
  player_character: "Personnage joueur",
  characteristic: "Caractéristique",
  specialized_stat: "Caractéristique spécialisée",
  injury: "Blessure",
  status_effect: "État",
  awakening: "Éveil",
  skill: "Compétence",
  mastery: "Maîtrise",
  magic: "Magie",
  spell: "Sort",
  affinity: "Affinité",
  invocation: "Invocation",
  contract: "Contrat",
  enchantment: "Enchantement",
  known_aptitude: "Aptitude connue",
  item: "Objet",
  inventory_item: "Objet d’inventaire",
  equipment: "Équipement",
  wallet: "Bourse",
  currency: "Monnaie",
  debt: "Dette",
  npc: "PNJ",
  relationship: "Relation",
  reputation: "Réputation",
  journal_entry: "Entrée de journal",
  mission: "Mission",
  quest: "Quête",
  knowledge: "Connaissance",
  rumor: "Rumeur",
  belief: "Croyance",
  faction: "Faction",
  organization: "Organisation",
  settlement: "Colonie",
  state: "État",
  kingdom: "Royaume",
  market: "Marché",
  economy_state: "État économique",
  conflict: "Conflit",
  world_event: "Événement mondial",
  environment_state: "État environnemental",
  resource_state: "État des ressources",
  infrastructure: "Infrastructure",
  law: "Loi",
  political_state: "État politique",
  place: "Lieu",
  map_marker: "Repère cartographique",
  current_location: "Position actuelle",
  region: "Région",
  route: "Route",
  dungeon: "Donjon",
  timeline_event: "Événement chronologique",
  historical_event: "Événement historique",
  adventurer_card: "Carte d’aventurier",
  evaluation: "Évaluation",
  certification: "Certification",
  monster: "Monstre",
  creature: "Créature",
  beast: "Bête",
  species: "Espèce",
  troop: "Troupe",
  unit: "Unité",
  military_unit: "Unité militaire",
  enemy_type: "Type d’ennemi",
  bestiary_entry: "Entrée de bestiaire",
  concept: "Concept",
  lore: "Savoir",
  religion: "Religion",
  language: "Langue",
  custom: "Coutume",
  dynasty: "Dynastie",
  lineage: "Lignée",
  kinship: "Lien de parenté",
  family_relation: "Lien familial",
  guild: "Guilde",
  hero: "Héros",
  notable: "Personnalité",
  leader: "Dirigeant",
  ruler: "Souverain",
  mentor: "Mentor",
  rival: "Rival",
};

const VALUE_LABELS: Record<string, string> = {
  true: "Oui",
  false: "Non",
  normal: "Normal",
  wounded: "Blessé",
  injured: "Blessé",
  sick: "Malade",
  ill: "Malade",
  fatigued: "Fatigué",
  exhausted: "Épuisé",
  healthy: "En bonne santé",
  active: "Actif",
  inactive: "Inactif",
  completed: "Terminée",
  complete: "Terminée",
  failed: "Échouée",
  pending: "En attente",
  open: "Ouvert",
  closed: "Fermé",
  unknown: "Inconnu",
  exact: "Exacte",
  approximate: "Approximative",
  rumored: "Rumeur",
  rumor: "Rumeur",
  belief: "Croyance",
  confirmed: "Confirmé",
  partial: "Partiel",
  low: "Faible",
  medium: "Moyen",
  high: "Élevé",
  male: "Masculin",
  female: "Féminin",
  other: "Autre",
  child: "Enfant",
  adolescent: "Adolescent",
  adult: "Adulte",
  elder: "Âgé",
  alive: "Vivant",
  dead: "Mort",
  friendly: "Amical",
  neutral: "Neutre",
  hostile: "Hostile",
  ally: "Allié",
  enemy: "Ennemi",
  friend: "Ami",
  family: "Famille",
  father: "Père",
  mother: "Mère",
  brother: "Frère",
  sister: "Sœur",
  parent: "Parent",
  sibling: "Fratrie",
  son: "Fils",
  daughter: "Fille",
};

const TOKEN_LABELS: Record<string, string> = {
  first: "prénom",
  last: "nom",
  current: "actuel",
  location: "lieu",
  known: "connu",
  description: "description",
  status: "statut",
  social: "social",
  biological: "biologique",
  stage: "stade",
  visual: "visuel",
  state: "état",
  player: "joueur",
  character: "personnage",
  world: "monde",
  event: "événement",
  historical: "historique",
  official: "officiel",
  rank: "rang",
  map: "carte",
  marker: "repère",
  relationship: "relation",
  knowledge: "connaissance",
  summary: "résumé",
  source: "source",
  confidence: "confiance",
  category: "catégorie",
  type: "type",
  name: "nom",
  family: "famille",
  strength: "force",
  strengths: "forces",
  weakness: "faiblesse",
  weaknesses: "faiblesses",
};

function sentenceCase(value: string) {
  if (!value) return value;
  return value.charAt(0).toLocaleUpperCase("fr") + value.slice(1);
}

export function fieldLabelFr(key: string): string {
  if (FIELD_LABELS[key]) return FIELD_LABELS[key];
  const translated = key.split("_").map((token) => TOKEN_LABELS[token] ?? token).join(" ");
  return sentenceCase(translated);
}

export function entityTypeLabelFr(type: string): string {
  return ENTITY_LABELS[type] ?? fieldLabelFr(type);
}

export function valueFr(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Oui" : "Non";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    const normalized = value.trim().toLocaleLowerCase("fr");
    return VALUE_LABELS[normalized] ?? value;
  }
  if (Array.isArray(value)) return value.map(valueFr).join(", ");
  if (typeof value === "object") {
    const localized = Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, nested]) => [fieldLabelFr(key), localizeForJson(nested)]));
    return JSON.stringify(localized);
  }
  return String(value);
}

function localizeForJson(value: unknown): unknown {
  if (value === null || value === undefined) return value;
  if (typeof value === "string") {
    const normalized = value.trim().toLocaleLowerCase("fr");
    return VALUE_LABELS[normalized] ?? value;
  }
  if (typeof value === "boolean") return value ? "Oui" : "Non";
  if (Array.isArray(value)) return value.map(localizeForJson);
  if (typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, nested]) => [fieldLabelFr(key), localizeForJson(nested)]));
  return value;
}
